// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmt7iVqaQHOy6rHW4L3E2uGfLksIvQFk',
    appId: '1:482064459537:web:a6bd5dcbb9075d4310ceb0',
    messagingSenderId: '482064459537',
    projectId: 'wien-tech-admin',
    authDomain: 'wien-tech-admin.firebaseapp.com',
    storageBucket: 'wien-tech-admin.firebasestorage.app',
    measurementId: 'G-YC06W475PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdx1MrwX1Izw3Yft16BzXV874jDT32H6E',
    appId: '1:482064459537:android:c0b269bdb5bb450010ceb0',
    messagingSenderId: '482064459537',
    projectId: 'wien-tech-admin',
    storageBucket: 'wien-tech-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY2QwUqzfUOKigtEPrqVE0FvJlNT2INuI',
    appId: '1:482064459537:ios:3fda0e2b413cd77c10ceb0',
    messagingSenderId: '482064459537',
    projectId: 'wien-tech-admin',
    storageBucket: 'wien-tech-admin.firebasestorage.app',
    iosBundleId: 'com.wientechnology.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY2QwUqzfUOKigtEPrqVE0FvJlNT2INuI',
    appId: '1:482064459537:ios:3fda0e2b413cd77c10ceb0',
    messagingSenderId: '482064459537',
    projectId: 'wien-tech-admin',
    storageBucket: 'wien-tech-admin.firebasestorage.app',
    iosBundleId: 'com.wientechnology.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmt7iVqaQHOy6rHW4L3E2uGfLksIvQFk',
    appId: '1:482064459537:web:895545b0943b24a610ceb0',
    messagingSenderId: '482064459537',
    projectId: 'wien-tech-admin',
    authDomain: 'wien-tech-admin.firebaseapp.com',
    storageBucket: 'wien-tech-admin.firebasestorage.app',
    measurementId: 'G-QTP61CKCHD',
  );

}